### ISSUE TITLE
About FF-Database Release Date

### ISSUE THREAD

**Issue by wmpscc** [zhaoyuzhi/ChildPredictor#1]
Very good work, thanks for your team's contribution.  Could you please release the original data as soon as possible, or align and crop the images with the desired of StyleGAN. I plan to evaluate our work with this dataset, and I will cite this paper.

**Comment by zhaoyuzhi** [comment]
We are discussing an appropriate approach to release the data. Please send me an email and we will get back to you shortly once the approach is done.

**Comment by wmpscc** [comment]
Thx.

**Comment by zhaoyuzhi** [comment]
Please check https://github.com/zhaoyuzhi/ChildPredictor#11-data-download for terms of use.

I will close this issue.
