### ISSUE TITLE
Gray output images

### ISSUE THREAD

**Issue by mcanan** [zhaoyuzhi/ChildPredictor#3]
I followed the steps in _3.3. Testing a Real Face_ but I am getting as output 320 gray images like this:

![image](https://user-images.githubusercontent.com/2572707/181331147-c633d0e7-961b-49a4-a25c-d0781609ef41.png)

I am using the downloaded weights and the default input images defined in the validation.yaml file.

Thanks

**Comment by zhaoyuzhi** [comment]
I tried it on my Windows 10 computer and it seems to work well. You can see the following information:
```
[INFO] LogHandlers setup!
22-07-28 14:07:53.993 : ********************* Validation Phase ************************
22-07-28 14:07:53.994 : => Import libs
22-07-28 14:07:54.012 : => Set validation data
22-07-28 14:07:54.015 : => Make models and load checkpoint
22-07-28 14:07:56.518 : Loading pytorch model from `Models/pretrain/ProGAN_pt_mixtureData_GAN_MSGAN_ACGAN.pth`.
22-07-28 14:07:56.652 : Successfully loaded!
22-07-28 14:07:56.653 :   `lod` of the loaded model is 0.0.
22-07-28 14:07:58.170 : ===> Use 1 GPUs
22-07-28 14:07:58.276 : ===> Load ckp for <Mapping_net> from E:\\code\\baby_model_pool\\mapping\\Mapping_Xencoder_full_ProGAN_GAN_MSGAN_ACGAN_deepArch_multi-gt_v4\\MappingNet_Batchsize_32_Epoch_298.pth
22-07-28 14:07:58.528 : => Begin to validate the model
```
But I found that I obtain a similar result with you on a Ubuntu computer. I am not sure the reason currently. I will try to figure it out.

**Comment by zhaoyuzhi** [comment]
Okay it seems that the ProGAN's weights provided are not correct.

Enter the `code` folder. You can simply do the following operations and re-run the main.py:
```
mkdir ./babymapping_1219/Models/pretrain
mv ./baby_model_pool/ProGAN-ckp/* ./babymapping_1219/Models/pretrain/
```

Hope this can address your issue.

**Comment by mcanan** [comment]
Great! Is working nice now!
Thank you.
